require: rubocop-rspec

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/*'
    # should be fixed soon or later
    - 'spec/controllers/application_controller_spec.rb'

Rails:
  Enabled: True

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    - 'lib/tasks/auto_annotate_models.rake'

RSpec/NestedGroups:
  Max: 4