version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=app
    ports:
      - 127.0.0.1:5432:5432
  maildev:
    image: 'djfarrelly/maildev'
    ports:
      - 127.0.0.1:1025:25
      - 127.0.0.1:1080:80
  # workers:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.dev
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     - PG_USER=postgres
  #     - PG_PASSWORD=app
  #     - PG_HOST=postgres
  #     - REDIS_URL=redis://redis
  #   command: 'sidekiq -q default -q mailers'
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    depends_on:
      - redis
      - postgres
      - maildev
    command: ["/srv/lib/docker/wait-for-it.sh", "database:5432", "--", "/srv/lib/docker/entrypoint.sh", "rails", "server", "--pid", "tmp/pids/server.development.pid"]
    environment:
      - MAILER_HOST=maildev
      - MAILER_PORT=25
      - PGUSER=postgres
      - PGPASSWORD=app
      - PGHOST=postgres
      - REDIS_URL=redis://redis
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/srv
  dep:
    image: busybox
    depends_on:
      - redis
      - postgres
      - maildev
    environment:
      - MAILER_HOST=maildev
      - MAILER_PORT=25
      - PGUSER=postgres
      - PGPASSWORD=app
      - PGHOST=postgres
      - REDIS_URL=redis://redis